# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "91c7ab6c0bf540201de82f5426f39592"
name = "qr-buy"
handle = "qr-buy-1"
application_url = "https://ate-aviation-ebony-files.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-2b3dc91d.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ate-aviation-ebony-files.trycloudflare.com/auth/callback",
  "https://ate-aviation-ebony-files.trycloudflare.com/auth/shopify/callback",
  "https://ate-aviation-ebony-files.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
